# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'course_4y' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for course_4y
  pod 'Cosmos', '~>23.0'

end
